# Computación científica en Python | Numpy | Pandas

### Instalar paquetes/librerias

Los paquetes que vamos a usar en este curso ya los tenenemos instalados con Anaconda en el entorno `base`. Para ver que paquetes tenemos instalados en el entorno `base` podemos mirarlo por el entorno gráfico que nos proporciona Anaconda, o a traves de la linea de comandos con el siguiente comando:

```
conda list
```

Para instalar paquetes que no vengan ya de serie, de nuevo dos opciones, usar la interfaz gráfica o la linea de comandos con alguno de los siguientes comandos:
```
conda install scikit-learn
pip install scikit-learn
```

## Numpy

* Numpy (numerical python) es uno de los paquetes más importantes de Python. 

* Muchos otros paquetes usan funcionalidades de este paquete de base. Por ese motivo, es importante conocer los conceptos básicos de Numpy.

* Numpy tiene un tipo de estructura especifico denominado `ndarray` que hace referencia a un vector/matríz N-dimensional.

Para importar el módulo Numpy a la sesión de Python en la que estamos trabajando:

In [1]:
import numpy as np

Importante: Los import de los módulos se suelen hacer al principio en los script de python.

Podemos ver todos los métodods asociados que tiene Numpy con la función `dir`:

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

Defininimos un `ndarray` con la función `np.array`:

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Cada `ndarray` está asociado a un tipo de dato (float, float32, float64, int, ...) y todos los objetos que lo forman tienen que ser de ese mismo tipo. Podemos ver que tipo de dato esta asociado a un `ndarray` con `dtype`:

In [6]:
a.dtype

dtype('int32')

Vamos a definir ahora una bi dimensional: 

In [7]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [8]:
b.dtype

dtype('float64')

In [9]:
b.shape

(2, 2)

In [10]:
b.ndim

2

In [11]:
b.size

4

Podemos definir `ndarray`s con más tipos de elementos:

In [12]:
c = np.array([['a', 'b'],['c', 'd']])
c

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [13]:
d = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

### Diferentes tipos de funciones para crear `ndarrays`:

In [14]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [19]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.random.random(3)

array([0.43122818, 0.29135981, 0.82425344])

In [22]:
np.random.random((3, 3))

array([[0.80545447, 0.39337949, 0.46895882],
       [0.37764337, 0.71051177, 0.45382529],
       [0.19417507, 0.16479578, 0.74048171]])

La función `reshape`:

In [23]:
np.arange(0,12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Operaciones aritméticas

In [24]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [25]:
a+4

array([4, 5, 6, 7])

In [26]:
a*2

array([0, 2, 4, 6])

In [27]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [28]:
a + b

array([ 4,  6,  8, 10])

In [29]:
a - b

array([-4, -4, -4, -4])

In [30]:
a * b

array([ 0,  5, 12, 21])

In [31]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

### Multiplicación de matrices

Hasta ahora, solo hemos hecho operaciones por elementos de los `ndarray`s. Ahora vamos a ver otro tipo de operaciones, como la multiplicación de matrices.

In [34]:
np.dot(A, B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [35]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [36]:
np.dot(B, A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

### Más funciones para las `ndarrays`

In [37]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [40]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [41]:
a.sum()

45

In [42]:
a.min()

1

In [43]:
a.max()

9

In [44]:
a.mean()

5.0

In [45]:
a.std()

2.581988897471611

### Manipular vectores y matrices

In [46]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[4]

5

In [48]:
a[-4]

6

In [49]:
a[:5]

array([1, 2, 3, 4, 5])

In [50]:
a[[1,2,8]]

array([2, 3, 9])

In [51]:
A = np.arange(1, 10).reshape((3, 3))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
A[1, 2]

6

In [53]:
A[:,0]

array([1, 4, 7])

In [54]:
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [55]:
A[[0,2], 0:2]

array([[1, 2],
       [7, 8]])

### Iterando un array

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9


In [58]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
for row in A:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [60]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9


Si necesitamos aplicar una función en las columnas o filas de una matriz, hay una forma más elegante y eficaz de hacerlo que usando un `for`.

In [61]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([4., 5., 6.])

In [62]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([2., 5., 8.])

### Condiciones y arrays de Booleanos

In [63]:
A = np.random.random((4, 4))
A

array([[0.85602406, 0.17439647, 0.82691213, 0.48981487],
       [0.9042295 , 0.99104976, 0.50913057, 0.15598115],
       [0.34064124, 0.97923316, 0.74593774, 0.53230547],
       [0.80176434, 0.45300678, 0.57819088, 0.14618446]])

In [64]:
A < 0.5

array([[False,  True, False,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [False,  True, False,  True]])

In [65]:
A[A < 0.5]

array([0.17439647, 0.48981487, 0.15598115, 0.34064124, 0.45300678,
       0.14618446])

### Unir arrays

In [66]:
A = np.ones((3, 3))
B = np.zeros((3, 3))

In [67]:
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.hstack((A, B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

Funciones más especificas para unir arrays de una sola dimensión y crear así arrays bidimensionales:

In [69]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [70]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [71]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Importante: Copía o vista de un elemento `ndarray`

In [72]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [73]:
b = a
b

array([1, 2, 3, 4])

In [74]:
a[2] = 0
a

array([1, 2, 0, 4])

In [75]:
b

array([1, 2, 0, 4])

In [76]:
c = a[0:2]
c

array([1, 2])

In [77]:
a[0] = 0
c

array([0, 2])

Evitamos esto usando la funcion `copy`.

In [78]:
a = np.array([1, 2, 3, 4])
b = a.copy()
b

array([1, 2, 3, 4])

In [79]:
a[2] = 0
b

array([1, 2, 3, 4])

In [80]:
c = a[0:2].copy()
c

array([1, 2])

In [81]:
a[0] = 0
c

array([1, 2])

## Pandas

* Pandas es el paquete de referencia para el análisis de datos en Python.

* Pandas proporciona estructuras de datos complejas y funciones especificas para trabajar con ellas.

* El concenpto fundamental de Pandas son los `DataFrame`, una estructura de datos con dos dimensiones. También están las `Series`, que son de una dimensión.

* Pandas usa Numpy

In [82]:
import numpy as np
import pandas as pd

### DataFrame

Un DataFrame es basicamente una tabla. Esta formado por filas y columnas, que son arrays con valores individuales (pueden ser números o no).

In [83]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2

In [84]:
pd.DataFrame({'Juan': ['Sopa', 'Pescado'], 'Ana': ['Pasta', 'Solomillo']})

Juan        Ana
0     Sopa      Pasta
1  Pescado  Solomillo

Estamos usando `pd.DataFrame()` para construir objetos `DataFrame`. Como argumento le pasamos un diccionario con los `keys` `['Juan', 'Ana']` y sus respectivos valores. Aunque este es el método más común para construir un objeto `DataFrame`, no es el único.

El método para construir `DataFrames` que hemos usado le asigna una etiqueta a cada columna que va desde el 0 hasta el número de columnas ascendentemente. Algunas veces esto está bien, pero otras veces puede que queramos asignar una etiqueta específica a cada columna.

In [85]:
pd.DataFrame({'Juan': ['Sopa', 'Pescado', 'Yogurt'], 'Ana': ['Pasta', 'Solomillo', 'Fruta']}, index=['1 Plato', '2 Plato', 'Postre'])

Juan        Ana
1 Plato     Sopa      Pasta
2 Plato  Pescado  Solomillo
Postre    Yogurt      Fruta

### Series

Las `Series` son una sequencia de datos. Si los `DataFrames` son tablas de datos, las `Series` son listas de datos.

In [86]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [87]:
pd.Series([30, 35, 40], index=['2015 matriculas', '2016 matriculas', '2017 matriculas'], name='Matriculas en máster de modelización')

2015 matriculas    30
2016 matriculas    35
2017 matriculas    40
Name: Matriculas en máster de modelización, dtype: int64

Las `Series` y los `DataFrames` están estrechamente relacionados. De hecho, podemos pensas que los `DataFrames` son simplemente un puñado de `Series` juntados.

### Leer ficheros de datos

Aunque exista la opción de crear los `DataFrames` y las `Series` a mano, lo más habitual va a ser que trabajemos con datos que ya existen y están recogidos en algún tipo de fichero (.xls, .csv, .json, ...)

El formato más habitual para guardar datos el el CSV. Los ficheros CSV contienen valores separados por comas.

In [88]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv")

In [89]:
reviews.shape

(129971, 14)

In [90]:
reviews.head()

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

In [91]:
reviews = pd.read_csv("data/winemag-data-130k-v2.csv", index_col=0)
reviews.head()

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

### Seleccionar subconjuntos del `DataFrame` o `Series`

Podemos seleccionar los valores de una o varias columnas de varias maneras.

In [92]:
reviews.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [93]:
reviews['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...   
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [94]:
reviews[['country', 'province']]

country           province
0          Italy  Sicily & Sardinia
1       Portugal              Douro
2             US             Oregon
3             US           Michigan
4             US             Oregon
...          ...                ...
129966   Germany              Mosel
129967        US             Oregon
129968    France             Alsace
129969    France             Alsace
129970    France             Alsace

[129971 rows x 2 columns]

In [95]:
reviews[['country', 'province']][:5]

country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro
2        US             Oregon
3        US           Michigan
4        US             Oregon

También podemos usar los indices para seleccionar los subconjuntos usando el método `iloc`.

In [96]:
reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [97]:
reviews.iloc[0,0]

'Italy'

In [98]:
reviews.iloc[:,-1]

0                                          Nicosia
1                              Quinta dos Avidagos
2                                        Rainstorm
3                                       St. Julian
4                                     Sweet Cheeks
                            ...                   
129966    Dr. H. Thanisch (Erben Müller-Burggraef)
129967                                    Citation
129968                             Domaine Gresser
129969                        Domaine Marcel Deiss
129970                            Domaine Schoffit
Name: winery, Length: 129971, dtype: object

In [99]:
reviews.iloc[-3:, :3]

country                                        description  \
129968  France  Well-drained gravel soil gives this wine its c...   
129969  France  A dry style of Pinot Gris, this is crisp with ...   
129970  France  Big, rich and off-dry, this is powered by inte...   

                          designation  
129968                          Kritt  
129969                            NaN  
129970  Lieu-dit Harth Cuvée Caroline

In [100]:
reviews.iloc[[0, 10, 100], 0]

0      Italy
10        US
100       US
Name: country, dtype: object

Por último, tambien podemos usar el método `loc` para usar las etiquetas de las filas y columnas.

In [101]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

CUIDADO! En este caso, las etiquetas de las filas son números, pero `iloc` y `loc` no funciónan igual. 

In [102]:
reviews.iloc[:5, 0]

0       Italy
1    Portugal
2          US
3          US
4          US
Name: country, dtype: object

In [103]:
reviews.loc[:5, 'country']

0       Italy
1    Portugal
2          US
3          US
4          US
5       Spain
Name: country, dtype: object

### Manipular el índice

In [104]:
reviews.set_index("title")

country  \
title                                                          
Nicosia 2013 Vulkà Bianco  (Etna)                      Italy   
Quinta dos Avidagos 2011 Avidagos Red (Douro)       Portugal   
Rainstorm 2013 Pinot Gris (Willamette Valley)             US   
St. Julian 2013 Reserve Late Harvest Riesling (...        US   
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...        US   
...                                                      ...   
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...   Germany   
Citation 2004 Pinot Noir (Oregon)                         US   
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)    France   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)         France   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...    France   

                                                                                          description  \
title                                                                                                   
Nicosia 2013 Vulkà Bianco  (Etna)                   Aromas include tropical fruit, broom, brimston...   
Quinta dos Avidagos 2011 Avidagos Red (Douro)       This is ripe and fruity, a wine that is smooth...   
Rainstorm 2013 Pinot Gris (Willamette Valley)       Tart and snappy, the flavors of lime flesh and...   
St. Julian 2013 Reserve Late Harvest Riesling (...  Pineapple rind, lemon pith and orange blossom ...   
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...  Much like the regular bottling from 2012, this...   
...                                                                                               ...   
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...  Notes of honeysuckle and cantaloupe sweeten th...   
Citation 2004 Pinot Noir (Oregon)                   Citation is given as much as a decade of bottl...   
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)  Well-drained gravel soil gives this wine its c...   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)       A dry style of Pinot Gris, this is crisp with ...   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...  Big, rich and off-dry, this is powered by inte...   

                                                                               designation  \
title                                                                                        
Nicosia 2013 Vulkà Bianco  (Etna)                                             Vulkà Bianco   
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                     Avidagos   
Rainstorm 2013 Pinot Gris (Willamette Valley)                                          NaN   
St. Julian 2013 Reserve Late Harvest Riesling (...                    Reserve Late Harvest   
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...      Vintner's Reserve Wild Child Block   
...                                                                                    ...   
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...  Brauneberger Juffer-Sonnenuhr Spätlese   
Citation 2004 Pinot Noir (Oregon)                                                      NaN   
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                   Kritt   
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                          NaN   
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...           Lieu-dit Harth Cuvée Caroline   

                                                    points  price  \
title                                                               
Nicosia 2013 Vulkà Bianco  (Etna)                       87    NaN   
Quinta dos Avidagos 2011 Avidagos Red (Douro)           87   15.0   
Rainstorm 2013 Pinot Gris (Willamette Valley)           87   14.0   
St. Julian 2013 Reserve Late Harvest Riesling (...      87   13.0   
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...      87   65.0   
...                                                    ...    ...   
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...      90   28.0   
Citation 2

### Selección condicional

Podemos buscar los vinos de Italia.

In [105]:
reviews['country'] == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...  
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

La anterior expresión nos ha devuelto una `Series` con los booleanos que nos dicen cuando el vino es Italiano. Para encontrar esas instancias devueltas por los booleanos hacemos:

In [106]:
reviews.loc[reviews['country'] == 'Italy']

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
6        Italy  Here's a bright, informal red that opens with ...   
13       Italy  This is dominated by oak and oak-driven aromas...   
22       Italy  Delicate aromas recall white flower and citrus...   
24       Italy  Aromas of prune, blackcurrant, toast and oak c...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  \
0                    Vulkà Bianco      87    NaN  Sicily & Sardinia   
6                         Belsito      87   16.0  Sicily & Sardinia   
13                          Rosso      87    NaN  Sicily & Sardinia   
22                      Ficiligno      87   19.0  Sicily & Sardinia   
24                          Aynat      87   35.0  Sicily & Sardinia   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              region_1 region_2    taster_name  \
0                                 Etna      NaN  Kerin O’Keefe   
6                             Vittoria      NaN  Kerin O’Keefe   
13                                Etna      NaN  Kerin O’Keefe   
22                             Sicilia      NaN  Kerin O’Keefe   
24                             Sicilia      NaN  Kerin O’Keefe   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       taster_twitter_handle  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title            variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...           Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...          Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...          Red Blend   
129961                        COS 2013 Frappato (Sicilia)           Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...       Nero d'Avola   

                                 winery  
0                               Nicosia  
6                       Terre di Giurfo  
13                  Masseria Setteporte  
22                

Si además de que sea Italiano, también queremos que nuestro vino tenga una puntuación mayor o igual a 90:

In [107]:
reviews.loc[(reviews['country'] == 'Italy') & (reviews['points'] >= 90)]

country                                        description  \
120      Italy  Slightly backward, particularly given the vint...   
130      Italy  At the first it was quite muted and subdued, b...   
133      Italy  Einaudi's wines have been improving lately, an...   
135      Italy  The color is just beginning to show signs of b...   
140      Italy  A big, fat, luscious wine with plenty of toast...   
...        ...                                                ...   
129929   Italy  This luminous sparkler has a sweet, fruit-forw...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                      designation  points  price           province  \
120           Bricco Rocche Prapó      92   70.0           Piedmont   
130         Bricco Rocche Brunate      91   70.0           Piedmont   
133                           NaN      91   68.0           Piedmont   
135                        Sorano      91   60.0           Piedmont   
140                   Costa Bruna      90   26.0           Piedmont   
...                           ...     ...    ...                ...   
129929                        NaN      91   38.0             Veneto   
129943                    Adènzia      90   29.0  Sicily & Sardinia   
129947                   Symposio      90   20.0  Sicily & Sardinia   
129961                        NaN      90   30.0  Sicily & Sardinia   
129962  Sàgana Tenuta San Giacomo      90   40.0  Sicily & Sardinia   

                              region_1 region_2    taster_name  \
120                             Barolo      NaN            NaN   
130                             Barolo      NaN            NaN   
133                             Barolo      NaN            NaN   
135                             Barolo      NaN            NaN   
140                     Barbera d'Alba      NaN            NaN   
...                                ...      ...            ...   
129929  Prosecco Superiore di Cartizze      NaN            NaN   
129943                         Sicilia      NaN  Kerin O’Keefe   
129947                 Terre Siciliane      NaN  Kerin O’Keefe   
129961                         Sicilia      NaN  Kerin O’Keefe   
129962                         Sicilia      NaN  Kerin O’Keefe   

       taster_twitter_handle  \
120                      NaN   
130                      NaN   
133                      NaN   
135                      NaN   
140                      NaN   
...                      ...   
129929                   NaN   
129943          @kerinokeefe   
129947          @kerinokeefe   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title       variety  \
120            Ceretto 2003 Bricco Rocche Prapó  (Barolo)      Nebbiolo   
130          Ceretto 2003 Bricco Rocche Brunate  (Barolo)      Nebbiolo   
133                     Poderi Luigi Einaudi 2003  Barolo      Nebbiolo   
135                 Giacomo Ascheri 2001 Sorano  (Barolo)      Nebbiolo   
140       Poderi Colla 2005 Costa Bruna  (Barbera d'Alba)       Barbera   
...                                                   ...           ...   
129929  Col Vetoraz Spumanti NV  Prosecco Superiore di...      Prosecco   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...     Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...     Red Blend   
129961                        COS 2013 Frappato (Sicilia)      Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...  Nero d'Avola   

                                 winery  
120                             Ceretto  
130                             Ceretto  
133                Poderi Luigi Einaudi  
135                     Giacomo Ascheri  
140                        Poderi Co

Si queremos un vino Italiano o con puntuación mayor o igual a 90:

In [108]:
reviews.loc[(reviews['country'] == 'Italy') | (reviews['points'] >= 90)]

country                                        description  \
0         Italy  Aromas include tropical fruit, broom, brimston...   
6         Italy  Here's a bright, informal red that opens with ...   
13        Italy  This is dominated by oak and oak-driven aromas...   
22        Italy  Delicate aromas recall white flower and citrus...   
24        Italy  Aromas of prune, blackcurrant, toast and oak c...   
...         ...                                                ...   
129966  Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967       US  Citation is given as much as a decade of bottl...   
129968   France  Well-drained gravel soil gives this wine its c...   
129969   France  A dry style of Pinot Gris, this is crisp with ...   
129970   France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
6                                      Belsito      87   16.0   
13                                       Rosso      87    NaN   
22                                   Ficiligno      87   19.0   
24                                       Aynat      87   35.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province  region_1      region_2         taster_name  \
0       Sicily & Sardinia      Etna           NaN       Kerin O’Keefe   
6       Sicily & Sardinia  Vittoria           NaN       Kerin O’Keefe   
13      Sicily & Sardinia      Etna           NaN       Kerin O’Keefe   
22      Sicily & Sardinia   Sicilia           NaN       Kerin O’Keefe   
24      Sicily & Sardinia   Sicilia           NaN       Kerin O’Keefe   
...                   ...       ...           ...                 ...   
129966              Mosel       NaN           NaN  Anna Lee C. Iijima   
129967             Oregon    Oregon  Oregon Other        Paul Gregutt   
129968             Alsace    Alsace           NaN          Roger Voss   
129969             Alsace    Alsace           NaN          Roger Voss   
129970             Alsace    Alsace           NaN          Roger Voss   

       taster_twitter_handle  \
0               @kerinokeefe   
6               @kerinokeefe   
13              @kerinokeefe   
22              @kerinokeefe   
24              @kerinokeefe   
...                      ...   
129966                   NaN   
129967           @paulgwine    
129968            @vossroger   
129969            @vossroger   
129970            @vossroger   

                                                    title            variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)        White Blend   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)           Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)  Nerello Mascalese   
22      Baglio di Pianetto 2007 Ficiligno White (Sicilia)        White Blend   
24            Canicattì 2009 Aynat Nero d'Avola (Sicilia)       Nero d'Avola   
...                                                   ...                ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...           Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)         Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...     Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)         Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...     Gewürztraminer   

                                          winery  
0                                        Nicosia  
6                                Terre di Giurfo  
13        

Si queremos un vino Italiano o Español:

In [109]:
reviews.loc[reviews['country'].isin(['Italy', 'Spain'])]

country                                        description  \
0        Italy  Aromas include tropical fruit, broom, brimston...   
5        Spain  Blackberry and raspberry aromas show a typical...   
6        Italy  Here's a bright, informal red that opens with ...   
13       Italy  This is dominated by oak and oak-driven aromas...   
18       Spain  Desiccated blackberry, leather, charred wood a...   
...        ...                                                ...   
129943   Italy  A blend of Nero d'Avola and Syrah, this convey...   
129947   Italy  A blend of 65% Cabernet Sauvignon, 30% Merlot ...   
129957   Spain  Lightly baked berry aromas vie for attention w...   
129961   Italy  Intense aromas of wild cherry, baking spice, t...   
129962   Italy  Blackberry, cassis, grilled herb and toasted a...   

                                              designation  points  price  \
0                                            Vulkà Bianco      87    NaN   
5                                            Ars In Vitro      87   15.0   
6                                                 Belsito      87   16.0   
13                                                  Rosso      87    NaN   
18      Vendimia Seleccionada Finca Valdelayegua Singl...      87   28.0   
...                                                   ...     ...    ...   
129943                                            Adènzia      90   29.0   
129947                                           Symposio      90   20.0   
129957                                            Crianza      90   17.0   
129961                                                NaN      90   30.0   
129962                          Sàgana Tenuta San Giacomo      90   40.0   

                 province          region_1 region_2        taster_name  \
0       Sicily & Sardinia              Etna      NaN      Kerin O’Keefe   
5          Northern Spain           Navarra      NaN  Michael Schachner   
6       Sicily & Sardinia          Vittoria      NaN      Kerin O’Keefe   
13      Sicily & Sardinia              Etna      NaN      Kerin O’Keefe   
18         Northern Spain  Ribera del Duero      NaN  Michael Schachner   
...                   ...               ...      ...                ...   
129943  Sicily & Sardinia           Sicilia      NaN      Kerin O’Keefe   
129947  Sicily & Sardinia   Terre Siciliane      NaN      Kerin O’Keefe   
129957     Northern Spain             Rioja      NaN  Michael Schachner   
129961  Sicily & Sardinia           Sicilia      NaN      Kerin O’Keefe   
129962  Sicily & Sardinia           Sicilia      NaN      Kerin O’Keefe   

       taster_twitter_handle  \
0               @kerinokeefe   
5                @wineschach   
6               @kerinokeefe   
13              @kerinokeefe   
18               @wineschach   
...                      ...   
129943          @kerinokeefe   
129947          @kerinokeefe   
129957           @wineschach   
129961          @kerinokeefe   
129962          @kerinokeefe   

                                                    title             variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)         White Blend   
5       Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   
6        Terre di Giurfo 2013 Belsito Frappato (Vittoria)            Frappato   
13                 Masseria Setteporte 2012 Rosso  (Etna)   Nerello Mascalese   
18      Pradorey 2010 Vendimia Seleccionada Finca Vald...   Tempranillo Blend   
...                                                   ...                 ...   
129943  Baglio del Cristo di Campobello 2012 Adènzia R...           Red Blend   
129947  Feudo Principi di Butera 2012 Symposio Red (Te...           Red Blend   
129957           Viñedos Real Rubio 2010 Crianza  (Rioja)   Tempranillo Blend   
129961                        COS 2013 Frappato (Sicilia)            Frappato   
129962  Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...        Nero d'Avola   

      

Si queremos deshacernos de las instancias en las que no tenemos el valor del precio:

In [110]:
reviews.loc[reviews['price'].notnull()]

country                                        description  \
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
5          Spain  Blackberry and raspberry aromas show a typical...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price        province  \
1                                     Avidagos      87   15.0           Douro   
2                                          NaN      87   14.0          Oregon   
3                         Reserve Late Harvest      87   13.0        Michigan   
4           Vintner's Reserve Wild Child Block      87   65.0          Oregon   
5                                 Ars In Vitro      87   15.0  Northern Spain   
...                                        ...     ...    ...             ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0           Mosel   
129967                                     NaN      90   75.0          Oregon   
129968                                   Kritt      90   30.0          Alsace   
129969                                     NaN      90   32.0          Alsace   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0          Alsace   

                   region_1           region_2         taster_name  \
1                       NaN                NaN          Roger Voss   
2         Willamette Valley  Willamette Valley        Paul Gregutt   
3       Lake Michigan Shore                NaN  Alexander Peartree   
4         Willamette Valley  Willamette Valley        Paul Gregutt   
5                   Navarra                NaN   Michael Schachner   
...                     ...                ...                 ...   
129966                  NaN                NaN  Anna Lee C. Iijima   
129967               Oregon       Oregon Other        Paul Gregutt   
129968               Alsace                NaN          Roger Voss   
129969               Alsace                NaN          Roger Voss   
129970               Alsace                NaN          Roger Voss   

       taster_twitter_handle  \
1                 @vossroger   
2                @paulgwine    
3                        NaN   
4                @paulgwine    
5                @wineschach   
...                      ...   
129966                   NaN   
129967           @paulgwine    
129968            @vossroger   
129969            @vossroger   
129970            @vossroger   

                                                    title             variety  \
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)      Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...          Pinot Noir   
5       Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   
...                                                   ...                 ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...            Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)          Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...      Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)          Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...      Gew

### Añadir datos

Añadir datos a nuestros `DataFrames` es fácil. Por ejemplo, podemos asignar el mismo valor a todas las instancias con el siguiente comando:

In [111]:
reviews['critic'] = 'everyone'
reviews['critic']

0         everyone
1         everyone
2         everyone
3         everyone
4         everyone
            ...   
129966    everyone
129967    everyone
129968    everyone
129969    everyone
129970    everyone
Name: critic, Length: 129971, dtype: object

In [112]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0         129971
1         129970
2         129969
3         129968
4         129967
           ...  
129966         5
129967         4
129968         3
129969         2
129970         1
Name: index_backwards, Length: 129971, dtype: int32

### Describir nuestro dataset

Pandas nos proporciona herramientas para facilmente conocer un poco por encima como es el dataset con el que estamos trabajando a traves de valores estadísticos.

In [113]:
reviews.describe()

points          price  index_backwards
count  129971.000000  120975.000000    129971.000000
mean       88.447138      35.363389     64986.000000
std         3.039730      41.022218     37519.540256
min        80.000000       4.000000         1.000000
25%        86.000000      17.000000     32493.500000
50%        88.000000      25.000000     64986.000000
75%        91.000000      42.000000     97478.500000
max       100.000000    3300.000000    129971.000000

In [114]:
reviews.describe(include='all')

country                                        description designation  \
count   129908                                             129971       92506   
unique      43                                             119955       37979   
top         US  Ripe plum, game, truffle, leather and menthol ...     Reserve   
freq     54504                                                  3        2009   
mean       NaN                                                NaN         NaN   
std        NaN                                                NaN         NaN   
min        NaN                                                NaN         NaN   
25%        NaN                                                NaN         NaN   
50%        NaN                                                NaN         NaN   
75%        NaN                                                NaN         NaN   
max        NaN                                                NaN         NaN   

               points          price    province     region_1       region_2  \
count   129971.000000  120975.000000      129908       108724          50511   
unique            NaN            NaN         425         1229             17   
top               NaN            NaN  California  Napa Valley  Central Coast   
freq              NaN            NaN       36247         4480          11065   
mean        88.447138      35.363389         NaN          NaN            NaN   
std          3.039730      41.022218         NaN          NaN            NaN   
min         80.000000       4.000000         NaN          NaN            NaN   
25%         86.000000      17.000000         NaN          NaN            NaN   
50%         88.000000      25.000000         NaN          NaN            NaN   
75%         91.000000      42.000000         NaN          NaN            NaN   
max        100.000000    3300.000000         NaN          NaN            NaN   

       taster_name taster_twitter_handle  \
count       103727                 98758   
unique          19                    15   
top     Roger Voss            @vossroger   
freq         25514                 25514   
mean           NaN                   NaN   
std            NaN                   NaN   
min            NaN                   NaN   
25%            NaN                   NaN   
50%            NaN                   NaN   
75%            NaN                   NaN   
max            NaN                   NaN   

                                                    title     variety  \
count                                              129971      129970   
unique                                             118840         707   
top     Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...  Pinot Noir   
freq                                                   11       13272   
mean                                                  NaN         NaN   
std                                                   NaN         NaN   
min                                                   NaN         NaN   
25%                                                   NaN         NaN   
50%                                                   NaN         NaN   
75%                                                   NaN         NaN   
max                                                   NaN         NaN   

                    winery    critic  index_backwards  
count               129971    129971    129971.000000  
unique               16757         1              NaN  
top     Wines & Winemakers  everyone              NaN  
freq                   222    129971              NaN  
mean                   NaN       NaN     64986.000000  
std                    NaN       NaN     37519.540256  
min                    NaN       NaN         1.000000  
25%                    NaN       NaN     32493.500000  
50%                    NaN       NaN     64986.000000  
75%                    NaN       NaN     97478.500000  
max                    NaN       NaN    129971.0000

In [115]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
critic                    object
index_backwards            int32
dtype: object

In [116]:
reviews['points'].mean()

88.44713820775404

In [117]:
reviews['points'].quantile(0.25)

86.0

In [118]:
reviews['country'].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

In [119]:
reviews['country'].value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedoni

### Modificar los valores de una columna

Por ejemplo, vamos a normalizar los datos de la columna points.

In [120]:
(reviews['points'] - reviews['points'].mean()) / reviews['points'].std()

0        -0.476075
1        -0.476075
2        -0.476075
3        -0.476075
4        -0.476075
            ...   
129966    0.510855
129967    0.510855
129968    0.510855
129969    0.510855
129970    0.510855
Name: points, Length: 129971, dtype: float64

In [121]:
reviews['province - region'] = reviews['province'] + ' - ' + reviews['region_1']
reviews

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer 

### Eliminar columnas

In [122]:
reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery', 'critic', 'index_backwards', 'province - region'],
      dtype='object')

In [123]:
reviews.pop('province - region')

0               Sicily & Sardinia - Etna
1                                    NaN
2             Oregon - Willamette Valley
3         Michigan - Lake Michigan Shore
4             Oregon - Willamette Valley
                       ...              
129966                               NaN
129967                   Oregon - Oregon
129968                   Alsace - Alsace
129969                   Alsace - Alsace
129970                   Alsace - Alsace
Name: province - region, Length: 129971, dtype: object

In [124]:
reviews = reviews.drop(columns=['critic', 'index_backwards'])
reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

### Agrupar datos

In [125]:
reviews.groupby('points')['points'].count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

Lo que ha ocurrido es que la función `groupby()` ha creado diferentes grupos dependiendo de la puntuación y luego a contado cuantos vinos hay en cada grupo.

Ahora, vamos a calcular el precio medio de los vinos dependiendo la puntuación:

In [126]:
reviews.groupby('points')['price'].mean()

points
80      16.372152
81      17.182353
82      18.870767
83      18.237353
84      19.310215
85      19.949562
86      22.133759
87      24.901884
88      28.687523
89      32.169640
90      36.906622
91      43.224252
92      51.037763
93      63.112216
94      81.436938
95     109.235420
96     159.292531
97     207.173913
98     245.492754
99     284.214286
100    485.947368
Name: price, dtype: float64

Podemos agrupar usando más de un criterio y devolver más de un valor con `agg()`.

In [127]:
reviews.groupby(['price', 'country']).agg(['count', 'min', 'mean', 'max'])

points                   
                  count min       mean max
price  country                            
4.0    Argentina      1  84  84.000000  84
       Romania        1  86  86.000000  86
       Spain          4  82  83.750000  85
       US             5  83  84.400000  86
5.0    Argentina      3  80  81.333333  84
...                 ...  ..        ...  ..
1900.0 France         1  98  98.000000  98
2000.0 France         2  96  96.500000  97
2013.0 US             1  91  91.000000  91
2500.0 France         2  96  96.000000  96
3300.0 France         1  88  88.000000  88

[2238 rows x 4 columns]

### Ordenar instancias

In [128]:
reviews.sort_values(by='points')

country                                        description  \
118056      US  This wine has very little going on aromaticall...   
35516       US  This Merlot has not fully ripened, with aromas...   
11086   France  Picture grandma standing over a pot of stewed ...   
11085   France  A white this age should be fresh and crisp; th...   
102482      US  This wine is a medium cherry-red color, with s...   
...        ...                                                ...   
111756  France  A hugely powerful wine, full of dark, brooding...   
89728   France  This latest incarnation of the famous brand is...   
89729   France  This new release from a great vintage for Char...   
118058      US  This wine dazzles with perfection. Sourced fro...   
111755  France  This is the finest Cheval Blanc for many years...   

                           designation  points   price              province  \
118056                         Reserve      80    26.0            California   
35516                              NaN      80    20.0            Washington   
11086                              NaN      80    11.0  Languedoc-Roussillon   
11085                              NaN      80     8.0      Southwest France   
102482                  Cabernet Franc      80    18.0            Washington   
...                                ...     ...     ...                   ...   
111756                             NaN     100   359.0              Bordeaux   
89728             Cristal Vintage Brut     100   250.0             Champagne   
89729   Le Mesnil Blanc de Blancs Brut     100   617.0             Champagne   
118058                         La Muse     100   450.0            California   
111755                             NaN     100  1500.0              Bordeaux   

                    region_1         region_2       taster_name  \
118056      Livermore Valley    Central Coast    Virginie Boone   
35516     Horse Heaven Hills  Columbia Valley  Sean P. Sullivan   
11086                  Fitou              NaN    Joe Czerwinski   
11085               Bergerac              NaN    Joe Czerwinski   
102482  Columbia Valley (WA)  Columbia Valley  Sean P. Sullivan   
...                      ...              ...               ...   
111756          Saint-Julien              NaN        Roger Voss   
89728              Champagne              NaN        Roger Voss   
89729              Champagne              NaN        Roger Voss   
118058         Sonoma County           Sonoma               NaN   
111755         Saint-Émilion              NaN        Roger Voss   

       taster_twitter_handle  \
118056               @vboone   
35516          @wawinereport   
11086                 @JoeCz   
11085                 @JoeCz   
102482         @wawinereport   
...                      ...   
111756            @vossroger   
89728             @vossroger   
89729             @vossroger   
118058                   NaN   
111755            @vossroger   

                                                    title  \
118056  3 Steves Winery 2008 Reserve Cabernet Sauvigno...   
35516        James Wyatt 2013 Merlot (Horse Heaven Hills)   
11086                         Mont Tauch 1998 Red (Fitou)   
11085         Seigneurs de Bergerac 1999 White (Bergerac)   
102482  Tucannon 2014 Cabernet Franc Rosé (Columbia Va...   
...                                                   ...   
111756      Château Léoville Las Cases 2010  Saint-Julien   
89728   Louis Roederer 2008 Cristal Vintage Brut  (Cha...   
89729   Salon 2006 Le Mesnil Blanc de Blancs Brut Char...   
118058            Verité 2007 La Muse Red (Sonoma County)   
111755           Château Cheval Blanc 2010  Saint-Émilion   

                         variety                      winery  
118056        Cabernet Sauvignon             3 Steves Winery  
35516                     Merlot                 James Wyatt  
11086                  Red Blend                  Mont Tauch  
11085                White Blend       Sei

In [129]:
reviews.sort_values(by='points', ascending=False).reset_index()

index    country                                        description  \
0       114972   Portugal  A powerful and ripe wine, strongly influenced ...   
1        89729     France  This new release from a great vintage for Char...   
2       113929         US  In 2005 Charles Smith introduced three high-en...   
3        45781      Italy  This gorgeous, fragrant wine opens with classi...   
4       123545         US  Initially a rather subdued Frog; as if it has ...   
...        ...        ...                                                ...   
129966  128255  Argentina  Severely compromised by green, minty, weedy ar...   
129967  128254  Argentina  Disappointing considering the source. The nose...   
129968   93686       Peru  Best on the nose, where apple and lemony aroma...   
129969   73865      Chile  There's not much point in making a reserve-sty...   
129970  128256         US  A hot, harsh and unbalance Chardonnay. Barely ...   

                           designation  points  price          province  \
0                     Nacional Vintage     100  650.0              Port   
1       Le Mesnil Blanc de Blancs Brut     100  617.0         Champagne   
2                           Royal City     100   80.0        Washington   
3                              Riserva     100  550.0           Tuscany   
4                          Bionic Frog     100   80.0        Washington   
...                                ...     ...    ...               ...   
129966                             NaN      80   13.0  Mendoza Province   
129967                     Gran Lurton      80   20.0  Mendoza Province   
129968                            Brut      80   15.0               Ica   
129969                   Prima Reserva      80   13.0      Maipo Valley   
129970                             NaN      80   24.0        California   

                       region_1         region_2        taster_name  \
0                           NaN              NaN         Roger Voss   
1                     Champagne              NaN         Roger Voss   
2          Columbia Valley (WA)  Columbia Valley       Paul Gregutt   
3        Brunello di Montalcino              NaN      Kerin O’Keefe   
4       Walla Walla Valley (WA)  Columbia Valley       Paul Gregutt   
...                         ...              ...                ...   
129966                  Mendoza              NaN  Michael Schachner   
129967                  Mendoza              NaN  Michael Schachner   
129968                      NaN              NaN  Michael Schachner   
129969                      NaN              NaN     Joe Czerwinski   
129970      Contra Costa County    Central Coast                NaN   

       taster_twitter_handle  \
0                 @vossroger   
1                 @vossroger   
2                @paulgwine    
3               @kerinokeefe   
4                @paulgwine    
...                      ...   
129966           @wineschach   
129967           @wineschach   
129968           @wineschach   
129969                @JoeCz   
129970                   NaN   

                                                    title             variety  \
0           Quinta do Noval 2011 Nacional Vintage  (Port)                Port   
1       Salon 2006 Le Mesnil Blanc de Blancs Brut Char...          Chardonnay   
2       Charles Smith 2006 Royal City Syrah (Columbia ...               Syrah   
3       Biondi Santi 2010 Riserva  (Brunello di Montal...          Sangiovese   
4       Cayuse 2008 Bionic Frog Syrah (Walla Walla Val...               Syrah   
...                                                   ...                 ...   
129966                    Viniterra 2007 Malbec (Mendoza)              Malbec   
129967  François Lurton 2006 Gran Lurton Cabernet Sauv...  Cabernet Sauvignon   
129968                   Tacama 2010 Brut Sparkling (Ica)     Sparkling Blend   
129969  De Martino 1999 Prima Reserva Merlot (Maipo Va...              Merlot   
129970   Bloomfiel

### Missing data

Tratar con los datos que faltan es muy importante. Pandas nos ofrece funciones como `isnull, notnull y fillna` para localizar y rellenar los valores perdidos.

In [130]:
reviews['country'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...  
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [131]:
reviews[reviews['country'].isnull()]

country                                        description  \
913        NaN  Amber in color, this wine has aromas of peach ...   
3131       NaN  Soft, fruity and juicy, this is a pleasant, si...   
4243       NaN  Violet-red in color, this semisweet wine has a...   
9509       NaN  This mouthwatering blend starts with a nose of...   
9750       NaN  This orange-style wine has a cloudy yellow-gol...   
...        ...                                                ...   
124176     NaN  This Swiss red blend is composed of four varie...   
129407     NaN  Dry spicy aromas of dusty plum and tomato add ...   
129408     NaN  El Capricho is one of Uruguay's more consisten...   
129590     NaN  A blend of 60% Syrah, 30% Cabernet Sauvignon a...   
129900     NaN  This wine offers a delightful bouquet of black...   

                           designation  points  price province region_1  \
913                     Asureti Valley      87   30.0      NaN      NaN   
3131                          Partager      83    NaN      NaN      NaN   
4243          Red Naturally Semi-Sweet      88   18.0      NaN      NaN   
9509    Theopetra Malagouzia-Assyrtiko      92   28.0      NaN      NaN   
9750         Orange Nikolaevo Vineyard      89   28.0      NaN      NaN   
...                                ...     ...    ...      ...      ...   
124176                    Les Romaines      90   30.0      NaN      NaN   
129407                         Reserve      89   22.0      NaN      NaN   
129408                         Reserve      89   22.0      NaN      NaN   
129590                            Shah      90   30.0      NaN      NaN   
129900                             NaN      91   32.0      NaN      NaN   

       region_2        taster_name taster_twitter_handle  \
913         NaN      Mike DeSimone        @worldwineguys   
3131        NaN         Roger Voss            @vossroger   
4243        NaN      Mike DeSimone        @worldwineguys   
9509        NaN    Susan Kostrzewa         @suskostrzewa   
9750        NaN       Jeff Jenssen        @worldwineguys   
...         ...                ...                   ...   
124176      NaN       Jeff Jenssen        @worldwineguys   
129407      NaN  Michael Schachner           @wineschach   
129408      NaN  Michael Schachner           @wineschach   
129590      NaN      Mike DeSimone        @worldwineguys   
129900      NaN      Mike DeSimone        @worldwineguys   

                                                    title             variety  \
913        Gotsa Family Wines 2014 Asureti Valley Chinuri             Chinuri   
3131                    Barton & Guestier NV Partager Red           Red Blend   
4243    Kakhetia Traditional Winemaking 2012 Red Natur...            Ojaleshi   
9509    Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...         White Blend   
9750    Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...          Chardonnay   
...                                                   ...                 ...   
124176            Les Frères Dutruy 2014 Les Romaines Red           Red Blend   
129407        El Capricho 2015 Reserve Cabernet Sauvignon  Cabernet Sauvignon   
129408               El Capricho 2015 Reserve Tempranillo         Tempranillo   
129590                            Büyülübağ 2012 Shah Red           Red Blend   
129900                                 Psagot 2014 Merlot              Merlot   

                                 winery  
913                  Gotsa Family Wines  
3131                  Barton & Guestier  
4243    Kakhetia Traditional Winemaking  
9509                           Tsililis  
9750                           Ross-idi  
...                                 ...  
124176                Les Frères Dutruy  
129407                      El Capricho  
129408                      El Capricho  
129590                        Büyülübağ  
129900                           Psagot  

[63 rows x 13 columns]

In [132]:
reviews['region_2'].fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...        
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [133]:
reviews['price'][reviews['price'].isnull()]

0        NaN
13       NaN
30       NaN
31       NaN
32       NaN
          ..
129844   NaN
129860   NaN
129863   NaN
129893   NaN
129964   NaN
Name: price, Length: 8996, dtype: float64

In [134]:
reviews['price'].fillna(method='bfill')

0         15.0
1         15.0
2         14.0
3         13.0
4         65.0
          ... 
129966    28.0
129967    75.0
129968    30.0
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

In [135]:
reviews['region_2'].fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...        
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

### Sustituir valores

In [136]:
reviews['taster_twitter_handle'].replace("@kerinokeefe", "@kerino")

0             @kerino
1          @vossroger
2         @paulgwine 
3                 NaN
4         @paulgwine 
             ...     
129966            NaN
129967    @paulgwine 
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

### Renombrar

Podemos renombrar los nombres de los indices o columnas con la función `rename`.

In [137]:
reviews.rename(columns={'points': 'score'})

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  score  price  \
0                                 Vulkà Bianco     87    NaN   
1                                     Avidagos     87   15.0   
2                                          NaN     87   14.0   
3                         Reserve Late Harvest     87   13.0   
4           Vintner's Reserve Wild Child Block     87   65.0   
...                                        ...    ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese     90   28.0   
129967                                     NaN     90   75.0   
129968                                   Kritt     90   30.0   
129969                                     NaN     90   32.0   
129970           Lieu-dit Harth Cuvée Caroline     90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer   

        

In [138]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

country                                        description  \
firstEntry      Italy  Aromas include tropical fruit, broom, brimston...   
secondEntry  Portugal  This is ripe and fruity, a wine that is smooth...   
2                  US  Tart and snappy, the flavors of lime flesh and...   
3                  US  Pineapple rind, lemon pith and orange blossom ...   
4                  US  Much like the regular bottling from 2012, this...   
...               ...                                                ...   
129966        Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967             US  Citation is given as much as a decade of bottl...   
129968         France  Well-drained gravel soil gives this wine its c...   
129969         France  A dry style of Pinot Gris, this is crisp with ...   
129970         France  Big, rich and off-dry, this is powered by inte...   

                                        designation  points  price  \
firstEntry                             Vulkà Bianco      87    NaN   
secondEntry                                Avidagos      87   15.0   
2                                               NaN      87   14.0   
3                              Reserve Late Harvest      87   13.0   
4                Vintner's Reserve Wild Child Block      87   65.0   
...                                             ...     ...    ...   
129966       Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                          NaN      90   75.0   
129968                                        Kritt      90   30.0   
129969                                          NaN      90   32.0   
129970                Lieu-dit Harth Cuvée Caroline      90   21.0   

                      province             region_1           region_2  \
firstEntry   Sicily & Sardinia                 Etna                NaN   
secondEntry              Douro                  NaN                NaN   
2                       Oregon    Willamette Valley  Willamette Valley   
3                     Michigan  Lake Michigan Shore                NaN   
4                       Oregon    Willamette Valley  Willamette Valley   
...                        ...                  ...                ...   
129966                   Mosel                  NaN                NaN   
129967                  Oregon               Oregon       Oregon Other   
129968                  Alsace               Alsace                NaN   
129969                  Alsace               Alsace                NaN   
129970                  Alsace               Alsace                NaN   

                    taster_name taster_twitter_handle  \
firstEntry        Kerin O’Keefe          @kerinokeefe   
secondEntry          Roger Voss            @vossroger   
2                  Paul Gregutt           @paulgwine    
3            Alexander Peartree                   NaN   
4                  Paul Gregutt           @paulgwine    
...                         ...                   ...   
129966       Anna Lee C. Iijima                   NaN   
129967             Paul Gregutt           @paulgwine    
129968               Roger Voss            @vossroger   
129969               Roger Voss            @vossroger   
129970               Roger Voss            @vossroger   

                                                         title  \
firstEntry                   Nicosia 2013 Vulkà Bianco  (Etna)   
secondEntry      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2                Rainstorm 2013 Pinot Gris (Willamette Valley)   
3            St. Julian 2013 Reserve Late Harvest Riesling ...   
4            Sweet Cheeks 2012 Vintner's Reserve Wild Child...   
...                                                        ...   
129966       Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...   
129967                       Citation 2004 Pinot Noir (Oregon)   
129968       Domaine Gresser 2013 Kritt Gewurztraminer (Als...   
129969           Domaine M

### Combinar datasets

In [139]:
df1 = reviews.iloc[:50000, :]
df2 = reviews.iloc[50000:, :]
df2.shape

(79971, 13)

In [140]:
pd.concat([df1, df2])

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer 

In [141]:
dfl = reviews.iloc[:, :8]
dfr = reviews.iloc[:, 8:]
dfr.shape

(129971, 5)

In [142]:
dfl.join(dfr)

country                                        description  \
0          Italy  Aromas include tropical fruit, broom, brimston...   
1       Portugal  This is ripe and fruity, a wine that is smooth...   
2             US  Tart and snappy, the flavors of lime flesh and...   
3             US  Pineapple rind, lemon pith and orange blossom ...   
4             US  Much like the regular bottling from 2012, this...   
...          ...                                                ...   
129966   Germany  Notes of honeysuckle and cantaloupe sweeten th...   
129967        US  Citation is given as much as a decade of bottl...   
129968    France  Well-drained gravel soil gives this wine its c...   
129969    France  A dry style of Pinot Gris, this is crisp with ...   
129970    France  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 Pinot Noir (Oregon)      Pinot Noir   
129968  Domaine Gresser 2013 Kritt Gewurztraminer (Als...  Gewürztraminer   
129969      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      Pinot Gris   
129970  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...  Gewürztraminer 

## Referencias
 - Iker y Mikel (UPV/EHU) lasaiker@fastmail.com, mikelbarrene@gmail.com